### ISSUE TITLE
Bamtools compile error - Sort.h "missing"

### ISSUE THREAD

**Issue by dwcloud** [jts/sga#40]
Getting an error compiling on CentOS 6.3, gcc 4.4.6-4.el6, using compiled Bamtools 1.0.2. There is no /api/algorithms folder in the final product, and I had tried placing the Sort.h code file in the bamtools ./src/api/algorithms/ directory; no go. Tried to re-compile on original CentOS5.8 system, this time with jemalloc, but it fails on the DPAlignment pragma issue now.

Any ideas? Thanks — Doug

btw you recently got an email from Amarin that spurred this posting. I'm the HPC applications admin. We had SGA running, but I had compiled it with hoard which presents memory issues on very large databases (crashes)...

g++ -DHAVE_CONFIG_H -I. -I..  -I../Util -I../Bigraph -I../SuffixTools -I../StringGraph -I../Concurrency -I../Algorithm -I../SQG -I../Scaffold -I../GraphDiff -I../Thirdparty -fopenmp -I/app/sga/sparsehash/include -I/app/sga/bamtools-1.0.2/include -I/app/sga/bamtools-1.0.2/include/bamtools -Wall -Wextra -Werror -O3 -MT sga-rewrite-evidence-bam.o -MD -MP -MF .deps/sga-rewrite-evidence-bam.Tpo -c -o sga-rewrite-evidence-bam.o `test -f 'rewrite-evidence-bam.cpp' || echo './'`rewrite-evidence-bam.cpp
In file included from rewrite-evidence-bam.cpp:18:
/app/sga/bamtools-1.0.2/include/api/algorithms/Sort.h: In static member function ‘static bool BamTools::Algorithms::Sort::sort_helper(const BamTools::Algorithms::Sort::Order&, const ElemType&, const ElemType&)’:
/app/sga/bamtools-1.0.2/include/api/algorithms/Sort.h:38: error: ‘BT_ASSERT_UNREACHABLE’ was not declared in this scope
make[2]: **\* [sga-rewrite-evidence-bam.o] Error 1
