### ISSUE TITLE
error: 'tr1/unordered_set' file not found

### ISSUE THREAD

**Issue by sjackman** [jts/sga#56]
SGA fails to compile with clang in OS X 10.9 and likely other C++11 compilers that have moved `unordered_set` from `std::tr1` to `std`.

```
clang++ -DHAVE_CONFIG_H -I. -I..  -I../Bigraph -I../Util -I../StringGraph -I../SQG -I../SuffixTools -I../Thirdparty -I../GraphDiff -I../Concurrency -I/usr/local/opt/google-sparsehash/include -I/usr/local/opt/bamtools/include -I/usr/local/opt/bamtools/include/bamtools -Wall -Wextra -Werror -Wno-unknown-pragmas -O3 -c -o libalgorithm_a-QCProcess.o `test -f 'QCProcess.cpp' || echo './'`QCProcess.cpp
OverlapAlgorithm.cpp:8:10: fatal error: 'tr1/unordered_set' file not found
#include <tr1/unordered_set>
         ^
1 error generated.
```
